const categories = {
  // Domaine QUANTIC
  "physics:quant-ph": { domain: "DOMAIN_QUANTIC", color: "quanticQuantPh" },

  // Domaine GRAVITATION
  "physics:gr-qc": { domain: "DOMAIN_GRAVITATION", color: "gravitationGrQc" },

  // Domaine COMPUTER_SCIENCE
  "cs:cs:AI": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csAI" },
  "cs:cs:LG": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csLG" },
  "cs:cs:CL": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCL" },
  "cs:cs:CV": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCV" },
  "cs:cs:IR": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csIR" },
  "cs:cs:DC": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDC" },
  "cs:cs:OS": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csOS" },
  "cs:cs:NI": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csNI" },
  "cs:cs:SY": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csSY" },
  "cs:cs:CC": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCC" },
  "cs:cs:DS": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDS" },
  "cs:cs:DM": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDM" },
  "cs:cs:ET": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csET" },
  "cs:cs:FL": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csFL" },
  "cs:cs:GT": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csGT" },
  "cs:cs:LO": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csLO" },
  "cs:cs:MA": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csMA" },
  "cs:cs:RO": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csRO" },
  "cs:cs:SD": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csSD" },
  "cs:cs:IT": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csIT" },
  "cs:cs:SE": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csSE" },
  "cs:cs:AR": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csAR" },
  "cs:cs:MM": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csMM" },
  "cs:cs:OH": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csOH" },
  "cs:cs:CE": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCE" },
  "cs:cs:CR": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCR" },
  "cs:cs:CG": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCG" },
  "cs:cs:HC": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csHC" },
  "cs:cs:DB": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDB" },
  "cs:cs:NE": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csNE" },
  "cs:cs:PF": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csPF" },
  "cs:cs:MS": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csMS" },

  // Domaine ECONOMICS
  "econ:econ:EM": { domain: "DOMAIN_ECONOMICS", color: "econEM" },
  "econ:econ:GN": { domain: "DOMAIN_ECONOMICS", color: "econGN" },
  "econ:econ:TH": { domain: "DOMAIN_ECONOMICS", color: "econTH" },

  // Domaine MATHEMATICS
  "math:math:AC": { domain: "DOMAIN_MATHEMATICS", color: "mathAC" },
  "math:math:AG": { domain: "DOMAIN_MATHEMATICS", color: "mathAG" },
  "math:math:GT": { domain: "DOMAIN_MATHEMATICS", color: "mathGT" },
  "math:math:RT": { domain: "DOMAIN_MATHEMATICS", color: "mathRT" },
  "math:math:AP": { domain: "DOMAIN_MATHEMATICS", color: "mathAP" },
  "math:math:CA": { domain: "DOMAIN_MATHEMATICS", color: "mathCA" },
  "math:math:SP": { domain: "DOMAIN_MATHEMATICS", color: "mathSP" },
  "math:math:PR": { domain: "DOMAIN_MATHEMATICS", color: "mathPR" },
  "math:math:ST": { domain: "DOMAIN_MATHEMATICS", color: "mathST" },
  "math:math:NT": { domain: "DOMAIN_MATHEMATICS", color: "mathNT" },
  "math:math:LO": { domain: "DOMAIN_MATHEMATICS", color: "mathLO" },
  "math:math:SG": { domain: "DOMAIN_MATHEMATICS", color: "mathSG" },
  "math:math:DG": { domain: "DOMAIN_MATHEMATICS", color: "mathDG" },
  "math:math:DS": { domain: "DOMAIN_MATHEMATICS", color: "mathDS" },
  "math:math:MG": { domain: "DOMAIN_MATHEMATICS", color: "mathMG" },
  "math:math:MP": { domain: "DOMAIN_MATHEMATICS", color: "mathMP" },
  "math:math:QA": { domain: "DOMAIN_MATHEMATICS", color: "mathQA" },
  "math:math:OC": { domain: "DOMAIN_MATHEMATICS", color: "mathOC" },
  "math:math:NA": { domain: "DOMAIN_MATHEMATICS", color: "mathNA" },
  "math:math:AT": { domain: "DOMAIN_MATHEMATICS", color: "mathAT" },
  "math:math:FA": { domain: "DOMAIN_MATHEMATICS", color: "mathFA" },
  "math:math:GM": { domain: "DOMAIN_MATHEMATICS", color: "mathGM" },
  "math:math:HO": { domain: "DOMAIN_MATHEMATICS", color: "mathHO" },
  "math:math:IT": { domain: "DOMAIN_MATHEMATICS", color: "mathIT" },
  "math:math:KT": { domain: "DOMAIN_MATHEMATICS", color: "mathKT" },
  "math:math:OA": { domain: "DOMAIN_MATHEMATICS", color: "mathOA" },
  "math:math:RA": { domain: "DOMAIN_MATHEMATICS", color: "mathRA" },
  "stat:stat:AP": { domain: "DOMAIN_MATHEMATICS", color: "statAP" },
  "stat:stat:ME": { domain: "DOMAIN_MATHEMATICS", color: "statME" },
  "stat:stat:TH": { domain: "DOMAIN_MATHEMATICS", color: "statTH" },
  "stat:stat:CO": { domain: "DOMAIN_MATHEMATICS", color: "statCO" },
  "stat:stat:ML": { domain: "DOMAIN_MATHEMATICS", color: "statML" },
  "stat:stat:OT": { domain: "DOMAIN_MATHEMATICS", color: "statOT" },

  // Domaine ASTROPHYSICS
  "physics:astro-ph:CO": { domain: "DOMAIN_ASTROPHYSICS", color: "astroCO" },
  "physics:astro-ph:GA": { domain: "DOMAIN_ASTROPHYSICS", color: "astroGA" },
  "physics:astro-ph:HE": { domain: "DOMAIN_ASTROPHYSICS", color: "astroHE" },
  "physics:astro-ph:EP": { domain: "DOMAIN_ASTROPHYSICS", color: "astroEP" },
  "physics:astro-ph:IM": { domain: "DOMAIN_ASTROPHYSICS", color: "astroIM" },
  "physics:astro-ph:SR": { domain: "DOMAIN_ASTROPHYSICS", color: "astroSR" },

  // Domaine CONDENSED_MATTER
  "physics:cond-mat:mtrl-sci": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatMtrlSci" },
  "physics:cond-mat:mes-hall": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatMesHall" },
  "physics:cond-mat:str-el": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatStrEl" },
  "physics:cond-mat:supr-con": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatSuprCon" },
  "physics:cond-mat:soft": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatSoft" },
  "physics:cond-mat:quant-gas": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatQuantGas" },
  "physics:cond-mat:stat-mech": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatStatMech" },
  "physics:cond-mat:other": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatOther" },
  "physics:cond-mat:dis-nn": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatDisNn" },

  // Domaine FUNDAMENTAL_PHYSICS
  "physics:hep-ex": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepEX" },
  "physics:hep-lat": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepLAT" },
  "physics:hep-ph": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepPH" },
  "physics:hep-th": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepTH" },
  "physics:math-ph": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "mathPH" },

  // Domaine NONLINEAR_PHYSICS
  "physics:nlin:CD": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinCD" },
  "physics:nlin:AO": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinAO" },
  "physics:nlin:CG": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinCG" },
  "physics:nlin:SI": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinSI" },
  "physics:nlin:PS": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinPS" },

  // Domaine NUCLEAR_PHYSICS
  "physics:nucl-ex": { domain: "DOMAIN_NUCLEAR_PHYSICS", color: "nuclEX" },
  "physics:nucl-th": { domain: "DOMAIN_NUCLEAR_PHYSICS", color: "nuclTH" },

  // Domaine QUANTITATIVE_BIOLOGY
  "q-bio:q-bio:BM": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioBM" },
  "q-bio:q-bio:GN": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioGN" },
  "q-bio:q-bio:NC": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioNC" },
  "q-bio:q-bio:MN": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioMN" },
  "q-bio:q-bio:CB": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioCB" },
  "q-bio:q-bio:QM": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioQM" },
  "q-bio:q-bio:PE": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioPE" },
  "q-bio:q-bio:SC": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioSC" },
  "q-bio:q-bio:TO": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioTO" },
  "q-bio:q-bio:OT": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioOT" },

  // Domaine APPLIED_PHYSICS
  "physics:physics:app-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "appPH" },
  "physics:physics:ao-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "aoPH" },
  "physics:physics:chem-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "chemPH" },
  "physics:physics:bio-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "bioPH" },
  "physics:physics:med-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "medPH" },
  "physics:physics:flu-dyn": { domain: "DOMAIN_APPLIED_PHYSICS", color: "fluDyn" },
  "physics:physics:plasm-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "plasmPH" },
  "physics:physics:optics": { domain: "DOMAIN_APPLIED_PHYSICS", color: "optics" },
  "physics:physics:comp-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "compPH" },
  "physics:physics:ins-det": { domain: "DOMAIN_APPLIED_PHYSICS", color: "insDet" },
  "physics:physics:atm-clus": { domain: "DOMAIN_APPLIED_PHYSICS", color: "atmClus" },
  "physics:physics:space-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "spacePH" },
  "physics:physics:geo-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "geoPH" },
  "physics:physics:gen-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "genPH" },
  "physics:physics:class-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "classPH" },
  "physics:physics:data-an": { domain: "DOMAIN_APPLIED_PHYSICS", color: "dataAn" },
  "physics:physics:hist-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "histPH" },
  "physics:physics:soc-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "socPH" },
  "physics:physics:pop-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "popPH" },
  "physics:physics:ed-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "edPH" },
  "physics:physics:acc-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "accPH" },

  // Domaine QUANTITATIVE_FINANCE
  "q-fin:q-fin:EC": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinEC" },
  "q-fin:q-fin:MF": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinMF" },
  "q-fin:q-fin:PM": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinPM" },
  "q-fin:q-fin:ST": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinST" },
  "q-fin:q-fin:RM": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinRM" },
  "q-fin:q-fin:PR": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinPR" },
  "q-fin:q-fin:TR": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinTR" },
  "q-fin:q-fin:CP": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinCP" },
  "q-fin:q-fin:GN": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinGN" },
};
