const categories = {
  // Domaine QUANTIC
  "physics:quant-ph": { domain: "DOMAIN_QUANTIC", color: "quanticQuantPh", label: "Quantum Physics" },

  // Domaine GRAVITATION
  "physics:gr-qc": { domain: "DOMAIN_GRAVITATION", color: "gravitationGrQc", label: "General Relativity" },

  // Domaine COMPUTER_SCIENCE
  "cs:cs:AI": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csAI", label: "Artificial Intelligence" },
  "cs:cs:LG": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csLG", label: "Machine Learning" },
  "cs:cs:CL": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCL", label: "Computational Linguistics" },
  "cs:cs:CV": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCV", label: "Computer Vision" },
  "cs:cs:IR": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csIR", label: "Information Retrieval" },
  "cs:cs:DC": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDC", label: "Data & Computation" },
  "cs:cs:OS": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csOS", label: "Operating Systems" },
  "cs:cs:NI": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csNI", label: "Networking & Internet" },
  "cs:cs:SY": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csSY", label: "Systems" },
  "cs:cs:CC": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCC", label: "Cloud Computing" },
  "cs:cs:DS": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDS", label: "Data Science" },
  "cs:cs:DM": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDM", label: "Distributed Systems" },
  "cs:cs:ET": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csET", label: "Emerging Tech" },
  "cs:cs:FL": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csFL", label: "Formal Languages" },
  "cs:cs:GT": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csGT", label: "Graph Theory" },
  "cs:cs:LO": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csLO", label: "Logic" },
  "cs:cs:MA": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csMA", label: "Mathematics in CS" },
  "cs:cs:RO": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csRO", label: "Robotics" },
  "cs:cs:SD": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csSD", label: "Software Design" },
  "cs:cs:IT": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csIT", label: "Information Theory" },
  "cs:cs:SE": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csSE", label: "Software Engineering" },
  "cs:cs:AR": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csAR", label: "Algorithms" },
  "cs:cs:MM": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csMM", label: "Multimedia" },
  "cs:cs:OH": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csOH", label: "Human-Computer Interaction" },
  "cs:cs:CE": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCE", label: "Computational Engineering" },
  "cs:cs:CR": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCR", label: "Cryptography" },
  "cs:cs:CG": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csCG", label: "Computer Graphics" },
  "cs:cs:HC": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csHC", label: "Human-Centered Computing" },
  "cs:cs:DB": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csDB", label: "Databases" },
  "cs:cs:NE": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csNE", label: "Networking" },
  "cs:cs:PF": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csPF", label: "Programming Fundamentals" },
  "cs:cs:MS": { domain: "DOMAIN_COMPUTER_SCIENCE", color: "csMS", label: "Machine Systems" },

  // Domaine ECONOMICS
  "econ:econ:EM": { domain: "DOMAIN_ECONOMICS", color: "econEM", label: "Econometrics" },
  "econ:econ:GN": { domain: "DOMAIN_ECONOMICS", color: "econGN", label: "General Economics" },
  "econ:econ:TH": { domain: "DOMAIN_ECONOMICS", color: "econTH", label: "Theory" },

  // Domaine MATHEMATICS
  "math:math:AC": { domain: "DOMAIN_MATHEMATICS", color: "mathAC", label: "Algebra & Combinatorics" },
  "math:math:AG": { domain: "DOMAIN_MATHEMATICS", color: "mathAG", label: "Algebraic Geometry" },
  "math:math:GT": { domain: "DOMAIN_MATHEMATICS", color: "mathGT", label: "Geometric Topology" },
  "math:math:RT": { domain: "DOMAIN_MATHEMATICS", color: "mathRT", label: "Representation Theory" },
  "math:math:AP": { domain: "DOMAIN_MATHEMATICS", color: "mathAP", label: "Applied Mathematics" },
  "math:math:CA": { domain: "DOMAIN_MATHEMATICS", color: "mathCA", label: "Category Theory" },
  "math:math:SP": { domain: "DOMAIN_MATHEMATICS", color: "mathSP", label: "Spectral Theory" },
  "math:math:PR": { domain: "DOMAIN_MATHEMATICS", color: "mathPR", label: "Probability" },
  "math:math:ST": { domain: "DOMAIN_MATHEMATICS", color: "mathST", label: "Statistics" },
  "math:math:NT": { domain: "DOMAIN_MATHEMATICS", color: "mathNT", label: "Number Theory" },
  "math:math:LO": { domain: "DOMAIN_MATHEMATICS", color: "mathLO", label: "Logic" },
  "math:math:SG": { domain: "DOMAIN_MATHEMATICS", color: "mathSG", label: "Signal Processing" },
  "math:math:DG": { domain: "DOMAIN_MATHEMATICS", color: "mathDG", label: "Differential Geometry" },
  "math:math:DS": { domain: "DOMAIN_MATHEMATICS", color: "mathDS", label: "Dynamical Systems" },
  "math:math:MG": { domain: "DOMAIN_MATHEMATICS", color: "mathMG", label: "Mathematical General" },
  "math:math:MP": { domain: "DOMAIN_MATHEMATICS", color: "mathMP", label: "Mathematical Physics" },
  "math:math:QA": { domain: "DOMAIN_MATHEMATICS", color: "mathQA", label: "Quantum Algebra" },
  "math:math:OC": { domain: "DOMAIN_MATHEMATICS", color: "mathOC", label: "Other Categories" },
  "math:math:NA": { domain: "DOMAIN_MATHEMATICS", color: "mathNA", label: "Numerical Analysis" },
  "math:math:AT": { domain: "DOMAIN_MATHEMATICS", color: "mathAT", label: "Algebraic Topology" },
  "math:math:FA": { domain: "DOMAIN_MATHEMATICS", color: "mathFA", label: "Functional Analysis" },
  "math:math:GM": { domain: "DOMAIN_MATHEMATICS", color: "mathGM", label: "Geometry & Mechanics" },
  "math:math:HO": { domain: "DOMAIN_MATHEMATICS", color: "mathHO", label: "Homological Algebra" },
  "math:math:IT": { domain: "DOMAIN_MATHEMATICS", color: "mathIT", label: "Information Theory" },
  "math:math:KT": { domain: "DOMAIN_MATHEMATICS", color: "mathKT", label: "K-Theory" },
  "math:math:OA": { domain: "DOMAIN_MATHEMATICS", color: "mathOA", label: "Operator Algebras" },
  "math:math:RA": { domain: "DOMAIN_MATHEMATICS", color: "mathRA", label: "Rational Analysis" },
  "stat:stat:AP": { domain: "DOMAIN_MATHEMATICS", color: "statAP", label: "Applied Probability" },
  "stat:stat:ME": { domain: "DOMAIN_MATHEMATICS", color: "statME", label: "Mathematical Economics" },
  "stat:stat:TH": { domain: "DOMAIN_MATHEMATICS", color: "statTH", label: "Theoretical Statistics" },
  "stat:stat:CO": { domain: "DOMAIN_MATHEMATICS", color: "statCO", label: "Combinatorics" },
  "stat:stat:ML": { domain: "DOMAIN_MATHEMATICS", color: "statML", label: "Machine Learning Theory" },
  "stat:stat:OT": { domain: "DOMAIN_MATHEMATICS", color: "statOT", label: "Other Statistics" },

  // Domaine ASTROPHYSICS
  "physics:astro-ph:CO": { domain: "DOMAIN_ASTROPHYSICS", color: "astroCO", label: "Cosmology" },
  "physics:astro-ph:GA": { domain: "DOMAIN_ASTROPHYSICS", color: "astroGA", label: "Galaxies" },
  "physics:astro-ph:HE": { domain: "DOMAIN_ASTROPHYSICS", color: "astroHE", label: "High Energy Astrophysics" },
  "physics:astro-ph:EP": { domain: "DOMAIN_ASTROPHYSICS", color: "astroEP", label: "Earth & Planetary" },
  "physics:astro-ph:IM": { domain: "DOMAIN_ASTROPHYSICS", color: "astroIM", label: "Instrumentation" },
  "physics:astro-ph:SR": { domain: "DOMAIN_ASTROPHYSICS", color: "astroSR", label: "Solar & Stellar" },

  // Domaine CONDENSED_MATTER
  "physics:cond-mat:mtrl-sci": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatMtrlSci", label: "Materials Science" },
  "physics:cond-mat:mes-hall": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatMesHall", label: "Mesoscopic & Hall Systems" },
  "physics:cond-mat:str-el": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatStrEl", label: "Strongly Correlated Electrons" },
  "physics:cond-mat:supr-con": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatSuprCon", label: "Superconductivity" },
  "physics:cond-mat:soft": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatSoft", label: "Soft Condensed Matter" },
  "physics:cond-mat:quant-gas": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatQuantGas", label: "Quantum Gases" },
  "physics:cond-mat:stat-mech": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatStatMech", label: "Statistical Mechanics" },
  "physics:cond-mat:other": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatOther", label: "Other Condensed Matter" },
  "physics:cond-mat:dis-nn": { domain: "DOMAIN_CONDENSED_MATTER", color: "condMatDisNn", label: "Disordered & Neural Networks" },

  // Domaine FUNDAMENTAL_PHYSICS
  "physics:hep-ex": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepEX", label: "High Energy Experiments" },
  "physics:hep-lat": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepLAT", label: "Lattice Field Theory" },
  "physics:hep-ph": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepPH", label: "Phenomenology" },
  "physics:hep-th": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "hepTH", label: "Theoretical High Energy" },
  "physics:math-ph": { domain: "DOMAIN_FUNDAMENTAL_PHYSICS", color: "mathPH", label: "Mathematical Physics" },

  // Domaine NONLINEAR_PHYSICS
  "physics:nlin:CD": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinCD", label: "Chaotic Dynamics" },
  "physics:nlin:AO": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinAO", label: "Adaptative Oscillations" },
  "physics:nlin:CG": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinCG", label: "Complex Geometry" },
  "physics:nlin:SI": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinSI", label: "Self-Interaction" },
  "physics:nlin:PS": { domain: "DOMAIN_NONLINEAR_PHYSICS", color: "nlinPS", label: "Pattern Formation" },

  // Domaine NUCLEAR_PHYSICS
  "physics:nucl-ex": { domain: "DOMAIN_NUCLEAR_PHYSICS", color: "nuclEX", label: "Nuclear Experiments" },
  "physics:nucl-th": { domain: "DOMAIN_NUCLEAR_PHYSICS", color: "nuclTH", label: "Nuclear Theory" },

  // Domaine QUANTITATIVE_BIOLOGY
  "q-bio:q-bio:BM": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioBM", label: "Biomolecules" },
  "q-bio:q-bio:GN": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioGN", label: "Genomics" },
  "q-bio:q-bio:NC": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioNC", label: "Neurons & Cognition" },
  "q-bio:q-bio:MN": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioMN", label: "Molecular Networks" },
  "q-bio:q-bio:CB": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioCB", label: "Cell Biology" },
  "q-bio:q-bio:QM": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioQM", label: "Quantitative Methods" },
  "q-bio:q-bio:PE": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioPE", label: "Population Ecology" },
  "q-bio:q-bio:SC": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioSC", label: "Structural Biology" },
  "q-bio:q-bio:TO": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioTO", label: "Tissue & Organs" },
  "q-bio:q-bio:OT": { domain: "DOMAIN_QUANTITATIVE_BIOLOGY", color: "qBioOT", label: "Other Biology" },

  // Domaine APPLIED_PHYSICS
  "physics:physics:app-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "appPH", label: "Applied Physics" },
  "physics:physics:ao-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "aoPH", label: "Acoustics & Optics" },
  "physics:physics:chem-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "chemPH", label: "Chemical Physics" },
  "physics:physics:bio-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "bioPH", label: "Biophysics" },
  "physics:physics:med-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "medPH", label: "Medical Physics" },
  "physics:physics:flu-dyn": { domain: "DOMAIN_APPLIED_PHYSICS", color: "fluDyn", label: "Fluid Dynamics" },
  "physics:physics:plasm-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "plasmPH", label: "Plasma Physics" },
  "physics:physics:optics": { domain: "DOMAIN_APPLIED_PHYSICS", color: "optics", label: "Optics" },
  "physics:physics:comp-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "compPH", label: "Computational Physics" },
  "physics:physics:ins-det": { domain: "DOMAIN_APPLIED_PHYSICS", color: "insDet", label: "Instrumentation & Detection" },
  "physics:physics:atm-clus": { domain: "DOMAIN_APPLIED_PHYSICS", color: "atmClus", label: "Atmospheric & Cluster Physics" },
  "physics:physics:space-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "spacePH", label: "Space Physics" },
  "physics:physics:geo-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "geoPH", label: "Geophysics" },
  "physics:physics:gen-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "genPH", label: "General Applied Physics" },
  "physics:physics:class-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "classPH", label: "Classical Physics" },
  "physics:physics:data-an": { domain: "DOMAIN_APPLIED_PHYSICS", color: "dataAn", label: "Data Analysis" },
  "physics:physics:hist-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "histPH", label: "History of Physics" },
  "physics:physics:soc-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "socPH", label: "Socio-Physics" },
  "physics:physics:pop-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "popPH", label: "Population Physics" },
  "physics:physics:ed-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "edPH", label: "Education Physics" },
  "physics:physics:acc-ph": { domain: "DOMAIN_APPLIED_PHYSICS", color: "accPH", label: "Accelerator Physics" },

  // Domaine QUANTITATIVE_FINANCE
  "q-fin:q-fin:EC": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinEC", label: "Econometrics" },
  "q-fin:q-fin:MF": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinMF", label: "Mutual Funds" },
  "q-fin:q-fin:PM": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinPM", label: "Portfolio Management" },
  "q-fin:q-fin:ST": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinST", label: "Statistical Trading" },
  "q-fin:q-fin:RM": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinRM", label: "Risk Management" },
  "q-fin:q-fin:PR": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinPR", label: "Pricing" },
  "q-fin:q-fin:TR": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinTR", label: "Trading" },
  "q-fin:q-fin:CP": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinCP", label: "Computational Finance" },
  "q-fin:q-fin:GN": { domain: "DOMAIN_QUANTITATIVE_FINANCE", color: "qFinGN", label: "General Finance" },

}
